import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import styles from '@/app/root.module.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className={styles.nav}>
          <div className={styles.links_container}>
              <Link href="/" className={styles.links}>My bio</Link>
          </div>
          <div className={styles.links_container}>
              <Link href="/contact" className={styles.links}>Contact</Link>
          </div>
          <div className={styles.links_container}>
              <Link href="/projects" className={styles.links}>Projects</Link>
          </div>
          <div className={styles.links_container}>
              <Link href="/timer" className={styles.links}>Timer</Link>
          </div>
          <div className={styles.links_container}>
              <Link href="/weather" className={styles.links}>Weather</Link>
          </div>
        </nav>
        <div className={styles.container}>
          <aside className={styles.aside}>
              <h3 className={styles.aside_title}>Favorite programming languages</h3>
              
                  <ul>
                      <li className={styles.aside_list}><Image className={styles.icons} width={48} height={48} src="/c++.svg" alt="C++ icon" />C++ </li>
                      <li className={styles.aside_list}><Image className={styles.icons} width={48} height={48} src="/C (CSharp).svg" alt="C# icon" />C#</li>
                      <li className={styles.aside_list}><Image className={styles.icons} width={48} height={48} src="/java.svg" alt="Java icon" />Java</li>
                  </ul>
            
          </aside>

          <main className={styles.main}>
          
            {children}
            
          </main>
        </div>
        <footer className={styles.footer}>
        <p> 2025.11.14 Jakub Masłowski</p>
        </footer>

      </body>
    </html>
  );
}
